version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks:
      - bdp-net
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka01:
    image: confluentinc/cp-kafka:7.3.0
    networks:
      - bdp-net
    container_name: kafka01
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka02:
    image: confluentinc/cp-kafka:7.3.0
    networks:
      - bdp-net
    container_name: kafka02
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02:9093,PLAINTEXT_INTERNAL://broker:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka03:
    image: confluentinc/cp-kafka:7.3.0
    networks:
      - bdp-net
    container_name: kafka03
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka03:9094,PLAINTEXT_INTERNAL://broker:29094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.1
    networks:
      - bdp-net
    depends_on:
      - kafka01
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/logstash-pipelines:/usr/share/logstash/pipeline
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"

  filebeat01:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat01
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat02:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat02
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat03:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat03
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat04:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat04
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat05:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat05
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro

  filebeat06:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat06
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat07:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat07
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat08:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat08
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat09:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat09
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro


  filebeat10:
    image: docker.elastic.co/beats/filebeat:8.6.1
    container_name: filebeat10
    command: filebeat -e -strict.perms=false
    networks:
      - bdp-net
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/:/var/log/:ro

networks:
  bdp-net:
    external: true