version: "2.2"

services:
# https://stackoverflow.com/a/66547784
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: always
    networks:
      - bdp-net
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1


  kibana:
    depends_on:
      - es01
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    restart: always
    networks:
      - bdp-net
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ENABLED_SECURITY=false
    mem_limit: ${KIBANA_MEM_LIMIT}

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local

networks:
  bdp-net:
    external: true